### PR TITLE
Contributions submitted for team CERBERUS

### PR DESCRIPTION
**Pull request by angelacmaio**
Adding open-source repositories and publications associated with Team CERBERUS.

Team CERBERUS contributors are welcome to submit PRs to the `cerberus` branch, including to add more open-source resources. Please see [docs/CONTRIBUTING.md](https://github.com/subtchallenge/subt_resources/blob/main/docs/CONTRIBUTING.md) for guidance. This PR will remain open until May 25, when it will be merged if no edits have been requested.

Tagging maintainers of linked repos:
@MihirDharmadhikari @lorenwel @schneith @helenol @fmina @maximilianwulf

### CODE REVIEW

**Comment by maximilianwulf** [comment]
Is there any action required from the maintainers?

**Comment by angelacmaio** [comment]
@maximilianwulf no action is required, but you are welcome to edit the descriptions of the repos in [1-Software.md](https://github.com/subtchallenge/subt_resources/blob/cerberus/1-Software.md) if you would like.

**Comment by lorenwel** [comment]
Opened an update PR #12

**Comment by marco-tranzatto** [comment]
Two additional PRs: #13  and #14

**Pull request merged**
